In [1]:
import keras
from keras.layers import Dense
from keras.models import Sequential 
from keras.utils import to_categorical

In [2]:
import pandas as pd
df=pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
target=df["target"]

In [5]:
target=to_categorical(target)

In [6]:
target

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [58]:
features=df.drop("target",axis=1)

In [59]:
df.head()


age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [73]:
features=features.values

In [74]:
features

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [75]:
num_cols=features.shape[1]

In [76]:
model=Sequential()
model.add(Dense(32,activation="relu",input_shape=(num_cols,)))
model.add(Dense(2,activation="softmax"))

In [77]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [78]:
model.fit(features,target,epochs=300)

Epoch 1/300
10/10 [==============================] - 0s 1ms/step - loss: 5.6956 - accuracy: 0.5479
Epoch 2/300
10/10 [==============================] - 0s 1ms/step - loss: 4.8023 - accuracy: 0.5710
Epoch 3/300
10/10 [==============================] - 0s 1ms/step - loss: 3.8423 - accuracy: 0.5677
Epoch 4/300
10/10 [==============================] - 0s 1ms/step - loss: 2.7397 - accuracy: 0.5578
Epoch 5/300
10/10 [==============================] - 0s 1ms/step - loss: 1.9186 - accuracy: 0.6106
Epoch 6/300
10/10 [==============================] - 0s 1ms/step - loss: 1.2826 - accuracy: 0.6073
Epoch 7/300
10/10 [==============================] - 0s 2ms/step - loss: 0.8763 - accuracy: 0.6304
Epoch 8/300
10/10 [==============================] - 0s 1ms/step - loss: 0.7216 - accuracy: 0.6667
Epoch 9/300
10/10 [==============================] - 0s 1ms/step - loss: 0.6520 - accuracy: 0.6898
Epoch 10/300
10/10 [==============================] - 0s 2ms/step - loss: 0.6322 - accuracy: 0.6667
Epoch 11/

In [79]:
df

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [80]:
newdata=np.array([57,0,0,140,241,0,1,163,1,0.6,2,0,2])

In [81]:
newdata.shape

(13,)

In [82]:
newdata=newdata.reshape(1,13)

In [83]:
newdata.shape

(1, 13)

In [84]:
model.predict(newdata)

array([[0.15137967, 0.8486203 ]], dtype=float32)